spring:
  datasource:
    url: jdbc:h2:file:/data/simple-bank
    username: simplebank-user
    password: simplebank-password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect